export function renderReceiptEmail({
  gymName,
  memberName,
  receiptNumber,
  amount,
  paymentMode,
  planName,
  startDate,
  endDate,
  upiRef,
}: {
  gymName: string;
  memberName: string;
  receiptNumber: string;
  amount: string;
  paymentMode: string;
  planName: string;
  startDate: string;
  endDate: string;
  upiRef?: string | null;
}) {
  const safeGym = escapeHtml(gymName);
  const safeFullName = escapeHtml(memberName);
  const safeFirstName = escapeHtml(firstNameOrFullName(memberName));
  const safeReceipt = escapeHtml(receiptNumber);
  const safeAmount = escapeHtml(amount);
  const safePlan = escapeHtml(planName || "your membership");
  const safePeriod = escapeHtml(`${startDate} → ${endDate}`);
  const safeMode = escapeHtml(paymentMode.toUpperCase());

  return `<!doctype html>
<html>
  <body style="margin:0;background:#f4f6f8;font-family:ui-sans-serif,system-ui,-apple-system,Segoe UI,Roboto,Helvetica,Arial;">
    <div style="max-width:560px;margin:0 auto;padding:24px;">
      <div style="background:#fff;border:1px solid #e4e4e7;border-radius:16px;padding:20px;box-shadow:0 1px 2px rgba(15,23,42,.08)">
        <div style="display:flex;align-items:center;gap:12px;margin-bottom:14px;">
          <div style="height:44px;width:44px;border-radius:999px;background:#eef2ff;color:#3730a3;display:flex;align-items:center;justify-content:center;font-weight:700;">
            ${escapeHtml(gymInitials(gymName))}
          </div>
          <div>
            <div style="font-size:12px;color:#64748b;">${safeGym}</div>
            <h1 style="margin:2px 0 0 0;font-size:18px;color:#0f172a;">Payment Confirmed ✓</h1>
          </div>
        </div>
        <p style="margin:0 0 16px 0;font-size:14px;color:#334155;">Hi ${safeFirstName}, thank you for your payment. Here’s your receipt:</p>

        <div style="display:block;border:1px solid #e4e4e7;border-radius:12px;overflow:hidden;">
          <div style="padding:12px 14px;background:#fafafa;border-bottom:1px solid #e4e4e7;">
            <div style="font-size:12px;color:#71717a;">Receipt</div>
            <div style="font-size:16px;font-weight:700;color:#18181b;">#${safeReceipt}</div>
          </div>
          <div style="padding:14px;">
            ${row("Member", safeFullName)}
            ${row("Plan", safePlan)}
            ${row("Period (IST)", safePeriod)}
            ${row("Amount paid", safeAmount)}
            ${row("Mode", safeMode)}
            ${upiRef ? row("UPI Ref", upiRef) : ""}
          </div>
        </div>

        <p style="margin:12px 0 0 0;font-size:14px;color:#334155;">Your membership is valid until ${escapeHtml(endDate)}. We’ll remind you a week before it expires — no surprises!</p>
        <p style="margin:10px 0 0 0;font-size:12px;color:#64748b;">This receipt is system-generated by ${safeGym}.</p>
      </div>
    </div>
  </body>
</html>`;
}

function row(label: string, value: string) {
  return `<div style="display:flex;justify-content:space-between;gap:12px;padding:8px 0;border-bottom:1px dashed #e4e4e7;">
    <div style="font-size:12px;color:#71717a;">${escapeHtml(label)}</div>
    <div style="font-size:12px;color:#18181b;font-weight:600;text-align:right;">${escapeHtml(
      value
    )}</div>
  </div>`;
}

function escapeHtml(input: string) {
  return input
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#039;");
}

function firstNameOrFullName(name: string): string {
  const trimmed = name.trim();
  if (!trimmed) return "Member";
  const first = trimmed.split(/\s+/)[0]?.trim();
  return first && first.length > 0 ? first : trimmed;
}

function gymInitials(gymName: string): string {
  const parts = gymName.trim().split(/\s+/).filter(Boolean);
  const raw = parts.map((p) => p[0] ?? "").join("");
  return (raw.slice(0, 2) || "GY").toUpperCase();
}

